CREATE SCHEMA IF NOT EXISTS supermercado_dw;


CREATE TABLE IF NOT EXISTS supermercado_dw.dim_fecha (
    sk_fecha      INTEGER PRIMARY KEY,
    fecha         DATE NOT NULL UNIQUE,
    num_semana    SMALLINT NOT NULL,
    mes           SMALLINT NOT NULL CHECK (mes BETWEEN 1 AND 12),
    nombre_mes    VARCHAR(15) NOT NULL,
    trimestre     SMALLINT NOT NULL CHECK (trimestre BETWEEN 1 AND 4),
    anio          SMALLINT NOT NULL,
    fecha_carga   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supermercado_dw.dim_producto (
    sk_producto        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto_origen INTEGER NOT NULL UNIQUE,
    nombre             VARCHAR(150),
    categoria          VARCHAR(100),
    subcategoria       VARCHAR(100),
    marca              VARCHAR(100),
    costo_unitario     NUMERIC(10,2),
    precio_lista       NUMERIC(10,2),
    fecha_carga        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supermercado_dw.dim_sucursal (
    sk_sucursal        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sucursal_origen INTEGER NOT NULL UNIQUE,
    nombre             VARCHAR(100),
    ciudad             VARCHAR(100),
    region             VARCHAR(100),
    tipo_sucursal      VARCHAR(50),
    fecha_carga        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supermercado_dw.dim_cliente (
    sk_cliente        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente_origen INTEGER NOT NULL UNIQUE,
    nombre            VARCHAR(150),
    segmento          VARCHAR(50),
    fecha_registro    DATE,
    ciudad            VARCHAR(100),
    fecha_carga       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supermercado_dw.dim_canal (
    sk_canal        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_canal_origen INTEGER NOT NULL UNIQUE,
    nombre          VARCHAR(50),
    fecha_carga     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supermercado_dw.dim_metodo_pago (
    sk_metodo_pago        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_metodo_pago_origen INTEGER NOT NULL UNIQUE,
    nombre                VARCHAR(50),
    fecha_carga           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS supermercado_dw.dim_promocion (
    sk_promocion        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_promocion_origen INTEGER UNIQUE,
    nombre              VARCHAR(150),
    tipo_descuento      VARCHAR(50),
    fecha_inicio        DATE,
    fecha_fin           DATE,
    alcance             VARCHAR(20),
    fecha_carga         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO supermercado_dw.dim_promocion (
    sk_promocion,
    id_promocion_origen,
    nombre,
    tipo_descuento,
    fecha_inicio,
    fecha_fin,
    alcance
)
VALUES (
    0,
    NULL,
    'Sin promoción',
    NULL,
    NULL,
    NULL,
    NULL
)
ON CONFLICT (sk_promocion) DO NOTHING;


CREATE TABLE IF NOT EXISTS supermercado_dw.fact_ventas (
    id_venta_detalle INTEGER PRIMARY KEY,
    id_venta         INTEGER NOT NULL,

    sk_fecha         INTEGER NOT NULL,
    sk_producto      INTEGER NOT NULL,
    sk_sucursal      INTEGER NOT NULL,
    sk_cliente       INTEGER NOT NULL,
    sk_canal         INTEGER NOT NULL,
    sk_metodo_pago   INTEGER NOT NULL,
    sk_promocion     INTEGER NOT NULL DEFAULT 0,

    cantidad_vendida INTEGER NOT NULL,
    precio_unitario  NUMERIC(10,2) NOT NULL,
    monto_descuento  NUMERIC(10,2) NOT NULL,
    monto_venta      NUMERIC(14,2) NOT NULL,
    costo_total      NUMERIC(14,2) NOT NULL,
    ganancia_bruta   NUMERIC(14,2) NOT NULL,

    fecha_carga      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_fact_ventas_fecha
        FOREIGN KEY (sk_fecha)
        REFERENCES supermercado_dw.dim_fecha(sk_fecha),

    CONSTRAINT fk_fact_ventas_producto
        FOREIGN KEY (sk_producto)
        REFERENCES supermercado_dw.dim_producto(sk_producto),

    CONSTRAINT fk_fact_ventas_sucursal
        FOREIGN KEY (sk_sucursal)
        REFERENCES supermercado_dw.dim_sucursal(sk_sucursal),

    CONSTRAINT fk_fact_ventas_cliente
        FOREIGN KEY (sk_cliente)
        REFERENCES supermercado_dw.dim_cliente(sk_cliente),

    CONSTRAINT fk_fact_ventas_canal
        FOREIGN KEY (sk_canal)
        REFERENCES supermercado_dw.dim_canal(sk_canal),

    CONSTRAINT fk_fact_ventas_metodo_pago
        FOREIGN KEY (sk_metodo_pago)
        REFERENCES supermercado_dw.dim_metodo_pago(sk_metodo_pago),

    CONSTRAINT fk_fact_ventas_promocion
        FOREIGN KEY (sk_promocion)
        REFERENCES supermercado_dw.dim_promocion(sk_promocion)
);

CREATE TABLE IF NOT EXISTS supermercado_dw.fact_inventario (
    sk_fecha                  INTEGER NOT NULL,
    sk_producto               INTEGER NOT NULL,
    sk_sucursal               INTEGER NOT NULL,

    stock_actual              INTEGER NOT NULL,
    stock_minimo              INTEGER NOT NULL,
    unidades_vendidas_semana  INTEGER NOT NULL,
    flag_quiebre              SMALLINT NOT NULL,
    flag_bajo_inventario      SMALLINT NOT NULL,

    fecha_carga               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_fact_inventario
        PRIMARY KEY (sk_fecha, sk_producto, sk_sucursal),

    CONSTRAINT fk_fact_inventario_fecha
        FOREIGN KEY (sk_fecha)
        REFERENCES supermercado_dw.dim_fecha(sk_fecha),

    CONSTRAINT fk_fact_inventario_producto
        FOREIGN KEY (sk_producto)
        REFERENCES supermercado_dw.dim_producto(sk_producto),

    CONSTRAINT fk_fact_inventario_sucursal
        FOREIGN KEY (sk_sucursal)
        REFERENCES supermercado_dw.dim_sucursal(sk_sucursal),

    CONSTRAINT ck_fact_inventario_stock_actual
        CHECK (stock_actual >= 0),

    CONSTRAINT ck_fact_inventario_stock_minimo
        CHECK (stock_minimo >= 0),

    CONSTRAINT ck_fact_inventario_unidades_semana
        CHECK (unidades_vendidas_semana >= 0),

    CONSTRAINT ck_fact_inventario_flag_quiebre
        CHECK (flag_quiebre IN (0, 1)),

    CONSTRAINT ck_fact_inventario_flag_bajo
        CHECK (flag_bajo_inventario IN (0, 1))
);


CREATE INDEX IF NOT EXISTS idx_fact_ventas_fecha
    ON supermercado_dw.fact_ventas(sk_fecha);

CREATE INDEX IF NOT EXISTS idx_fact_ventas_producto
    ON supermercado_dw.fact_ventas(sk_producto);

CREATE INDEX IF NOT EXISTS idx_fact_ventas_sucursal
    ON supermercado_dw.fact_ventas(sk_sucursal);

CREATE INDEX IF NOT EXISTS idx_fact_ventas_cliente
    ON supermercado_dw.fact_ventas(sk_cliente);

CREATE INDEX IF NOT EXISTS idx_fact_inventario_producto
    ON supermercado_dw.fact_inventario(sk_producto);

CREATE INDEX IF NOT EXISTS idx_fact_inventario_sucursal
    ON supermercado_dw.fact_inventario(sk_sucursal);
